version: "3.8"

services:
  postgres_db:
    image: postgres:16
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: pgdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  mysql_data:
  postgres_data:
